# Generated by Django 2.1.5 on 2019-02-03 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rfp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('due_date', models.DateField()),
                ('subject', models.CharField(max_length=256)),
            ],
        ),
    ]
