# Generated by Django 2.1.5 on 2019-02-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfp_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='subject',
            field=models.TextField(),
        ),
    ]
